### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by IlyaMokin** [PashaPunko/messenger#1]
@PashaPunko Thanks, looking good, a few notes which we need to fix
![image](https://user-images.githubusercontent.com/5592397/87878667-6a3cf280-c9ee-11ea-832f-9be4e2b3e30c.png)

When it will be ready just put an update in the ticket - we are monitoring it

**Comment by PashaPunko** [comment]
Everything is fixed now, I hope.

**Comment by ilya4321** [comment]
Yes, thank you. Looks good. Will be checking your JS tasks soon.
